# Generated by Django 3.2.6 on 2021-09-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
